# Домашная работа 2

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.
4. Пришлите на почту *ml-teachers* ссылку на этот файл в вашем репозитории.
5. В теме письма указать `ML Homework #2: Name Surname`. Если тема будет неправильная, то задание не будет проверено.

**Дедлайн: 3.11.2017 6:00 OMSK**

## Numpy

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np
np.__version__

'1.13.1'

2) Создать нулевой вектор размера 10

In [2]:
np.zeros((10, 1))

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

3) Создать вектор заполненный 7-ами размера 7

In [3]:
np.full((7,1), 7)

array([[7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7]])

4) Создать вектор заполненный четными числами от 10 до 100

In [4]:
vect = np.array(np.linspace(10,100,46))
vect.reshape(vect.size,1)

array([[  10.],
       [  12.],
       [  14.],
       [  16.],
       [  18.],
       [  20.],
       [  22.],
       [  24.],
       [  26.],
       [  28.],
       [  30.],
       [  32.],
       [  34.],
       [  36.],
       [  38.],
       [  40.],
       [  42.],
       [  44.],
       [  46.],
       [  48.],
       [  50.],
       [  52.],
       [  54.],
       [  56.],
       [  58.],
       [  60.],
       [  62.],
       [  64.],
       [  66.],
       [  68.],
       [  70.],
       [  72.],
       [  74.],
       [  76.],
       [  78.],
       [  80.],
       [  82.],
       [  84.],
       [  86.],
       [  88.],
       [  90.],
       [  92.],
       [  94.],
       [  96.],
       [  98.],
       [ 100.]])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [5]:
arr1 = np.random.random_sample(5)
print(arr1)
arr2 = arr1
print(arr2)
i = 0
k = arr1.size - 1
while 1:
    arr2[i] = arr1[k]
    i += 1;
    k -= 1;
    if (k == -1):
        break;
print(arr2)

[ 0.0722899   0.75755988  0.12877827  0.1267466   0.77156702]
[ 0.0722899   0.75755988  0.12877827  0.1267466   0.77156702]
[ 0.77156702  0.1267466   0.12877827  0.1267466   0.77156702]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [6]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [7]:
arr1 = np.eye(3)
arr2 = np.zeros((3,1))
arr3 = np.concatenate((arr2,arr1), axis=1)
arr4 = np.zeros((1,4))
np.concatenate((arr3,arr4))

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [8]:
arr1 = np.diag([-6,-5,-4,-3])
arr2 = np.full((4,4), 7)
arr1 + arr2

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [9]:
arr1 = np.arange(5)
arr1 = arr1.reshape(1,5)
arr2 = arr1
for i in range(2):
    arr2 = np.concatenate((arr2,arr2), axis=0)
arr2 = np.concatenate((arr2,arr1), axis=0)
print(arr2)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [10]:
arr1 = np.random.random_sample((10,10))
arr1 = arr1 - arr1.mean(axis=1).reshape(10,1)
print(arr1)

[[ 0.20832814 -0.0994083   0.01836704 -0.29950017 -0.17281919 -0.19443016
   0.46071596  0.13228245  0.14732009 -0.20085587]
 [-0.0123934  -0.19133405 -0.14249599 -0.1473253  -0.06844252  0.2497715
  -0.15295751  0.32945654 -0.03554872  0.17126945]
 [ 0.09247319 -0.41173124 -0.15599231  0.44058585 -0.39860822  0.40093911
  -0.1398705  -0.39509186  0.32051847  0.24677752]
 [-0.01620151  0.25397311  0.08980288  0.06596614 -0.38963946  0.20564782
   0.22451193  0.06268526 -0.35803863 -0.13870754]
 [ 0.38606803  0.20410939 -0.49071673  0.25453091  0.34129181 -0.09868031
   0.23146919 -0.15222895 -0.44124098 -0.23460234]
 [ 0.20028473  0.20248192 -0.47436419  0.02970268 -0.09914977  0.11525445
   0.06413538 -0.02149889  0.03537004 -0.05221636]
 [-0.27332217 -0.35467618  0.17692474 -0.36357648 -0.27353984 -0.15462325
   0.30955428  0.42743283  0.46963866  0.03618742]
 [-0.27556744 -0.27915946  0.29000774 -0.39777652 -0.48763619  0.4693749
   0.10417354 -0.07552688  0.41547922  0.23663109]
 [

12) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца

In [11]:
arr1 = np.random.random_sample((10,10))
arr1 = arr1 - np.median(arr1,axis=0).reshape(1,10)
print(arr1)

[[-0.19765046 -0.05424499 -0.15871529  0.1829953   0.51587804  0.31542071
  -0.21754997 -0.05407139  0.34348292 -0.33215266]
 [ 0.56086863  0.05424499 -0.06848336 -0.11908399 -0.28544882  0.08572466
  -0.07421663  0.49628479 -0.01092755 -0.30257401]
 [ 0.0512704  -0.21995097 -0.18984715  0.19993603  0.07895447 -0.04960762
  -0.101484   -0.47177923 -0.32662946 -0.16874982]
 [-0.2296972   0.22720424  0.59500203  0.11908399 -0.08497332  0.20619094
   0.05179721 -0.103603    0.26796964 -0.08074458]
 [-0.0512704  -0.2106108   0.65472076 -0.5659656  -0.08944659 -0.07759031
   0.09995957 -0.25449493 -0.31623248  0.30249274]
 [ 0.14399357 -0.15095693  0.11501424  0.17628114  0.07868275 -0.12067175
   0.14727347 -0.11628109  0.01092755  0.17083503]
 [-0.22825057 -0.34909687 -0.20946437 -0.47605782  0.41814172 -0.39412933
  -0.09831899  0.1508766   0.60368675 -0.42158631]
 [ 0.20833936  0.15071842  0.06848336 -0.20768668 -0.07868275  0.04960762
  -0.05179721  0.05407139  0.39349987  0.1529915 ]


13) Создать матрицу случайных чисел 5x5. Добавить к ней столбцы максимумов и минимумов по строкам. Получится матрица 5x7.

In [12]:
arr1 = np.random.random_sample((5,5))
arrMax = np.max(arr1, axis=1).reshape(5,1)
arrMin = np.min(arr1, axis=1).reshape(5,1)
arr1 = np.concatenate((arr1,arrMax), axis=1)
arr1 = np.concatenate((arr1,arrMin), axis=1)
print(arr1)

[[  5.40963965e-01   5.29935368e-01   9.51772548e-01   8.43772146e-01
    1.22133060e-01   9.51772548e-01   1.22133060e-01]
 [  4.72469753e-01   2.65232370e-01   6.99527488e-01   9.47958742e-01
    1.02251876e-01   9.47958742e-01   1.02251876e-01]
 [  2.32280189e-01   4.44546058e-01   3.11830472e-01   4.11887591e-04
    5.04156925e-01   5.04156925e-01   4.11887591e-04]
 [  8.85211289e-01   9.49458722e-01   7.92513997e-01   2.83824280e-01
    1.09166097e-01   9.49458722e-01   1.09166097e-01]
 [  8.25621482e-02   4.25880126e-02   6.37224400e-01   3.02112453e-04
    3.46097673e-01   6.37224400e-01   3.02112453e-04]]


14) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрицы. Найти произведение этих матриц. Найти обратную матрицу этого произведения.

In [13]:
vect = np.arange(1,51)
vect = vect.reshape(50, 1)
vectN = vect[::2]
vectN = vectN.reshape(5,5)
vectC = vect[1::2]
vectC = vectC.reshape(5,5)
res = vectC * vectN
print(res)

[[   2   12   30   56   90]
 [ 132  182  240  306  380]
 [ 462  552  650  756  870]
 [ 992 1122 1260 1406 1560]
 [1722 1892 2070 2256 2450]]


15) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [14]:
arr1 = np.arange(49)
arr1 = arr1 % 2
arr2 = arr1.reshape(7,7)
arr3 = arr1[1:8]
arr3 = arr3.reshape(1,7)
arr4 = arr1[1:9]
arr4 = arr4.reshape(8,1)
arr5 = np.concatenate((arr2,arr3), axis=0)
arr6 = np.concatenate((arr5,arr4), axis=1)
print(arr6)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Pandas

#### Полезная литература

- http://pandas.pydata.org/pandas-docs/stable/10min.html
- https://pandas.pydata.org/pandas-docs/stable/indexing.html
- https://pandas.pydata.org/pandas-docs/stable/missing_data.html

В этом задании мы с вами рассмотрим датасет [Adult Data Set](https://archive.ics.uci.edu/ml/datasets/Adult).
Основывается он на данных переписи населения 1994 года в США.

Расшифровка содержимого колонок:

- age: continuous. 
- workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked. 
- fnlwgt: continuous. sampling weight, more here: SIPP Weighting.
- education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool. 
- education-num: continuous. 
- marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse. 
- occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces. 
- relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried. 
- race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black. 
- sex: Female, Male. 
- capital-gain: continuous. Income from investment sources, apart from wages/salary.
- capital-loss: continuous. Losses from investment sources, apart from wages/salary.
- hours-per-week: continuous. 
- native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.

In [15]:
%matplotlib inline
import pandas as pd
pd.__version__

'0.20.3'

In [49]:
df = pd.read_csv('./data/adult.csv.gz', compression='gzip', na_values='?')
df.head()

age         workclass  fnlwgt     education  education.num marital.status  \
0    90               NaN   77053       HS-grad              9        Widowed   
1    82           Private  132870       HS-grad              9        Widowed   
2    66               NaN  186061  Some-college             10        Widowed   
3    54           Private  140359       7th-8th              4       Divorced   
4    41           Private  264663  Some-college             10      Separated   
5    34           Private  216864       HS-grad              9       Divorced   
6    38           Private  150601          10th              6      Separated   
7    74         State-gov   88638     Doctorate             16  Never-married   
8    68       Federal-gov  422013       HS-grad              9       Divorced   
9    41           Private   70037  Some-college             10  Never-married   
10   45           Private  172274     Doctorate             16       Divorced   
11   38  Self-emp-not-inc  164526   Prof-school             15  Never-married   
12   52           Private  129177     Bachelors             13        Widowed   

           occupation    relationship   race     sex  capital.gain  \
0                 NaN   Not-in-family  White  Female             0   
1     Exec-managerial   Not-in-family  White  Female             0   
2                 NaN       Unmarried  Black  Female             0   
3   Machine-op-inspct       Unmarried  White  Female             0   
4      Prof-specialty       Own-child  White  Female             0   
5       Other-service       Unmarried  White  Female             0   
6        Adm-clerical       Unmarried  White    Male             0   
7      Prof-specialty  Other-relative  White  Female             0   
8      Prof-specialty   Not-in-family  White  Female             0   
9        Craft-repair       Unmarried  White    Male             0   
10     Prof-specialty       Unmarried  Black  Female             0   
11     Prof-specialty   Not-in-family  White    Male             0   
12      Other-service   Not-in-family  White  Female             0   

    capital.loss  hours.per.week native.country income  
0           4356              40  United-States  <=50K  
1           4356              18  United-States  <=50K  
2           4356              40  United-States  <=50K  
3           3900              40  United-States  <=50K  
4           3900              40  United-States  <=50K  
5           3770              45  United-States  <=50K  
6           3770              40  United-States  <=50K  
7           3683              20  United-States   >50K  
8           3683              40  United-States  <=50K  
9           3004              60            NaN   >50K  
10          3004              35  United-States   >50K  
11          2824              45  United-States   >50K  
12          2824              20  United-States   >50K

1) Выведите последние 10 элеметнов датасета

In [54]:
df1 = df.sort_index(axis=0, level=None, ascending=False, inplace=False, kind='quicksort', na_position='last', sort_remaining=True, by=None)
df1.head(10)

age         workclass  fnlwgt     education  education.num  \
32560   22           Private  201490       HS-grad              9   
32559   58           Private  151910       HS-grad              9   
32558   40           Private  154374       HS-grad              9   
32557   27           Private  257302    Assoc-acdm             12   
32556   22           Private  310152  Some-college             10   
32555   53           Private  321865       Masters             14   
32554   32           Private  116138       Masters             14   
32553   43           Private   84661     Assoc-voc             11   
32552   32           Private   34066          10th              6   
32551   43  Self-emp-not-inc   27242  Some-college             10   

           marital.status         occupation   relationship  \
32560       Never-married       Adm-clerical      Own-child   
32559             Widowed       Adm-clerical      Unmarried   
32558  Married-civ-spouse  Machine-op-inspct        Husband   
32557  Married-civ-spouse       Tech-support           Wife   
32556       Never-married    Protective-serv  Not-in-family   
32555  Married-civ-spouse    Exec-managerial        Husband   
32554       Never-married       Tech-support  Not-in-family   
32553  Married-civ-spouse              Sales        Husband   
32552  Married-civ-spouse  Handlers-cleaners        Husband   
32551  Married-civ-spouse       Craft-repair        Husband   

                     race     sex  capital.gain  capital.loss  hours.per.week  \
32560               White    Male             0             0              20   
32559               White  Female             0             0              40   
32558               White    Male             0             0              40   
32557               White  Female             0             0              38   
32556               White    Male             0             0              40   
32555               White    Male             0             0              40   
32554  Asian-Pac-Islander    Male             0             0              11   
32553               White    Male             0             0              45   
32552  Amer-Indian-Eskimo    Male             0             0              40   
32551               White    Male             0             0              50   

      native.country income  
32560  United-States  <=50K  
32559  United-States  <=50K  
32558  United-States   >50K  
32557  United-States  <=50K  
32556  United-States  <=50K  
32555  United-States   >50K  
32554         Taiwan  <=50K  
32553  United-States  <=50K  
32552  United-States  <=50K  
32551  United-States  <=50K

2) Сколько колонок и сколько строк в этом датасете?

In [18]:
df.shape

(32561, 15)

3) Какие типы данных у элементов этого датасета?

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
age               32561 non-null int64
workclass         30725 non-null object
fnlwgt            32561 non-null int64
education         32561 non-null object
education.num     32561 non-null int64
marital.status    32561 non-null object
occupation        30718 non-null object
relationship      32561 non-null object
race              32561 non-null object
sex               32561 non-null object
capital.gain      32561 non-null int64
capital.loss      32561 non-null int64
hours.per.week    32561 non-null int64
native.country    31978 non-null object
income            32561 non-null object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


4) Какие признаки имеют пропуски?

In [20]:
df.describe(percentiles=None, include='all', exclude=None)

age workclass        fnlwgt education  education.num  \
count   32561.000000     30725  3.256100e+04     32561   32561.000000   
unique           NaN         8           NaN        16            NaN   
top              NaN   Private           NaN   HS-grad            NaN   
freq             NaN     22696           NaN     10501            NaN   
mean       38.581647       NaN  1.897784e+05       NaN      10.080679   
std        13.640433       NaN  1.055500e+05       NaN       2.572720   
min        17.000000       NaN  1.228500e+04       NaN       1.000000   
25%        28.000000       NaN  1.178270e+05       NaN       9.000000   
50%        37.000000       NaN  1.783560e+05       NaN      10.000000   
75%        48.000000       NaN  2.370510e+05       NaN      12.000000   
max        90.000000       NaN  1.484705e+06       NaN      16.000000   

            marital.status      occupation relationship   race    sex  \
count                32561           30718        32561  32561  32561   
unique                   7              14            6      5      2   
top     Married-civ-spouse  Prof-specialty      Husband  White   Male   
freq                 14976            4140        13193  27816  21790   
mean                   NaN             NaN          NaN    NaN    NaN   
std                    NaN             NaN          NaN    NaN    NaN   
min                    NaN             NaN          NaN    NaN    NaN   
25%                    NaN             NaN          NaN    NaN    NaN   
50%                    NaN             NaN          NaN    NaN    NaN   
75%                    NaN             NaN          NaN    NaN    NaN   
max                    NaN             NaN          NaN    NaN    NaN   

        capital.gain  capital.loss  hours.per.week native.country income  
count   32561.000000  32561.000000    32561.000000          31978  32561  
unique           NaN           NaN             NaN             41      2  
top              NaN           NaN             NaN  United-States  <=50K  
freq             NaN           NaN             NaN          29170  24720  
mean     1077.648844     87.303830       40.437456            NaN    NaN  
std      7385.292085    402.960219       12.347429            NaN    NaN  
min         0.000000      0.000000        1.000000            NaN    NaN  
25%         0.000000      0.000000       40.000000            NaN    NaN  
50%         0.000000      0.000000       40.000000            NaN    NaN  
75%         0.000000      0.000000       45.000000            NaN    NaN  
max     99999.000000   4356.000000       99.000000            NaN    NaN

5) Как вы думаете, с чем связаны пропуски этих значение. Напишите развернутый ответ в ячейке ниже.

**ответ: **

6) Какие и сколько различных рабочих классов `workclass` представлено в выборке?

In [21]:
df.workclass.astype('category').values

[NaN, Private, NaN, Private, Private, ..., Private, Private, Private, Private, Private]
Length: 32561
Categories (8, object): [Federal-gov, Local-gov, Never-worked, Private, Self-emp-inc, Self-emp-not-inc, State-gov, Without-pay]

7) Какой средний возраст женщин и мужчин?

In [22]:
print("Female avg age: {}\nMale avg age: {}".format(
    df[df['sex'] == 'Female']['age'].mean(),
    df[df['sex'] == 'Male']['age'].mean()
))

Female avg age: 36.85823043357163
Male avg age: 39.43354749885268


8) Постройте гистограмму(bar) распределения образования людей (education)

9) Каковы средние значения и среднеквадратичные отклонения возраста тех, кто получает более 50K в год (признак income) и тех, кто получает менее 50K в год?

In [30]:
df1 = df.groupby(by='income')
dfL = df1.get_group('<=50K')
print(dfL['age'].mean())
dfM = df1.get_group('>50K')
print(dfM['age'].mean())
print(dfL['age'].std())
print(dfM['age'].std())

36.78373786407767
44.24984058155847
14.020088490824829
10.519027719851769


10) Правда ли, что люди, которые получают больше 50k, имеют как минимум высшее образование? (признак education - Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters или Doctorate)

In [85]:
i = 0
for val in dfM['education']:
    if (val != 'Bachelors'):
        if (val != 'Prof-school'):
            if (val != 'Assoc-acdm'):
                if (val != 'Assoc-voc'):
                    if (val != 'Masters'):
                        if (val != 'Doctorate'):
                            i = 1;
if (i == 1):
    print('False')

False


11) Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак marital-status)? Женатыми считаем тех, у кого marital-status начинается с Married (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.

In [105]:
dfMale = dfM.groupby(by='sex')
dfMale = dfMale.get_group('Male')
mar = 0;
notMar = 0;
for val in dfMale['marital.status']:
    if (val != 'Married-civ-spouse'):
        if (val != 'Married-spouse-absent'):
            if (val != 'Married-AF-spouse'):
                notMar += 1;
            else:
                mar += 1;
        else:
            mar += 1;
    else:
        mar += 1;
if (mar > notMar):
    print('Married')
else:
    print('Not married')

Married


12) Посчитайте среднее время работы (hours-per-week) зарабатывающих мало и много (salary) для каждой страны (native-country).

13) Постройте сводную таблицу для сравнения уровня образования и разницы между capital.gain и capital.loss (то есть пассивный доход). Сделайте так, чтобы `capital.gain - capital.loss` создали не больше 10 разных уникальных значений.

14) Женщины из каких стран получают в среднем большую зарплату (>50K) чаще.

15) Создайте случайную колонку - `magic_salary`, которую нужно будет вычислить следующим образом: если зарплата небольшая (<50K), тогда случайно выберите число из диапазона [0,50]. Если зарплата выше 50K тогда из диапазона [51, 200]. Посчитайте среднюю зарплату в час для групп людей с одни уровнем образования на основе нашей случайной колонки `magic_salary`